scrollback_lines 5000

notify_on_cmd_finish unfocused

cursor_trail 200
cursor_trai_decay 0.1 0.4
cursor_trail_start_threshold 2


# BEGIN_KITTY_THEME
# moonlight
include current-theme.conf
# END_KITTY_THEME